abstract final class OrderStages {
  static const tabs = [
    'New',
    'Ready to Ship',
    'Ready to Pickup',
    'In-Transit',
    'Delivered',
    'Cancelled',
    'RTO',
    'All',
  ];
  static const statuses = [
    'New',
    'Out for Pickup',
    'Pickup Error',
    'Pickup Exception',
    'Pickup Queued',
    'Pickup Rescheduled',
    'Pickup Scheduled',
    'Ready to Ship',
    'Searching for Rider',
    'Pickup Completed',
    'Partially Completed',
    'Damaged',
    'Delayed',
    'Destroyed',
    'In Transit',
    'Out for Delivery',
    'Picked Up',
    'Reached Destination Hub',
    'Delivered',
    'Undelivered',
    'On Hold',
    'Connection Aligned',
    'Custom Cleared',
    'In Flight',
    'In Transit Overseas',
    'Reached Overseas Warehouse',
    'Custom Cleared Overseas',
    'Overdue Orders',
    'RTO Initiated',
    'RTO Delivered',
    'RTO Acknowledged',
    'RTO Rejected',
    'RTO In Transit',
    'RTO NDR',
    'Cancelled',
    'Lost',
    'Not Serviceable',
    'Exception',
    'Self Drop-Off',
    'Seized',
    'ODA Self Pickup',
  ];
  static String label(String stage) =>
      stage == 'In-Transit' ? 'In Transit' : stage;
}
